
service: scheduler
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1


functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post

